name: Laravel Auto Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install --no-dev --optimize-autoloader || true

      - name: Run Migrations

        run: php artisan config:clear
          php artisan migrate --force

      - name: Clear Cache
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:clear
